name: ✨ Feature Request
description: 提出新功能或改进建议 / Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！好的想法让项目更好。
        Thanks for your suggestion! Great ideas make the project better.

  - type: textarea
    id: problem
    attributes:
      label: Problem / 你遇到了什么问题？
      description: 描述你想解决的问题或痛点
      placeholder: 我经常需要 ... 但是目前 ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / 你期望的解决方案
      description: 描述你理想中的功能表现
      placeholder: 如果能支持 ... 就好了
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / 你考虑过的替代方案
      description: 你是否尝试过其他方式来解决这个问题？

  - type: dropdown
    id: scope
    attributes:
      label: Scope / 涉及范围
      options:
        - MDX-Net / Roformer Runner
        - Demucs Runner
        - VR Architecture Runner
        - Docker / Deployment
        - CLI / User Experience
        - Model Management
        - Documentation
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / 补充信息
      description: 其他参考资料、截图、相关项目链接等
