#!/bin/bash
# ==============================================================================
# UVR Headless Runner - Installation Script
# ==============================================================================
# This script installs native-style CLI wrappers so you can run:
#   uvr-mdx -m "Kim Vocal 2" -i song.wav -o output/
#   uvr-demucs -m htdemucs -i song.wav -o output/
#   uvr-vr -m "UVR-De-Echo-Normal" -i song.wav -o output/
#
# Without needing to type `docker run` commands!
#
# Usage:
#   ./docker/install.sh              # Install with auto-detected GPU support
#   ./docker/install.sh --cpu        # Force CPU-only installation
#   ./docker/install.sh --gpu        # Force GPU installation
#   ./docker/install.sh --uninstall  # Remove installed wrappers
#
# ==============================================================================

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INSTALL_DIR="${UVR_INSTALL_DIR:-/usr/local/bin}"
MODELS_DIR="${UVR_MODELS_DIR:-${HOME}/.uvr_models}"
IMAGE_NAME="uvr-headless"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ------------------------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------------------------
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_banner() {
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║        UVR Headless Runner - Installation Script              ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        echo "  https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running or you don't have permission."
        echo "  Try: sudo systemctl start docker"
        echo "  Or add your user to docker group: sudo usermod -aG docker \$USER"
        exit 1
    fi
}

detect_gpu() {
    # Check for NVIDIA GPU and Docker GPU support
    if command -v nvidia-smi &> /dev/null && nvidia-smi &> /dev/null; then
        # Check if nvidia-container-toolkit is installed
        if docker info 2>/dev/null | grep -q "nvidia"; then
            echo "gpu"
            return
        fi
        # Try running a GPU container
        if docker run --rm --gpus all nvidia/cuda:12.4.1-base-ubuntu22.04 nvidia-smi &> /dev/null; then
            echo "gpu"
            return
        fi
    fi
    echo "cpu"
}

# ------------------------------------------------------------------------------
# Build Docker Image
# ------------------------------------------------------------------------------
build_image() {
    local target="$1"
    local tag="${IMAGE_NAME}:${target}"
    
    log_info "Building Docker image: ${tag}"
    log_info "This may take several minutes on first build..."
    
    cd "${PROJECT_ROOT}"
    
    if docker build -t "${tag}" -f docker/Dockerfile --target "${target}" .; then
        log_success "Image built successfully: ${tag}"
    else
        log_error "Failed to build image"
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# Create CLI Wrapper Scripts
# ------------------------------------------------------------------------------
create_wrapper() {
    local cmd_name="$1"
    local runner_script="$2"
    local target="$3"
    local wrapper_path="${INSTALL_DIR}/${cmd_name}"
    
    log_info "Creating wrapper: ${cmd_name}"
    
    cat > "/tmp/${cmd_name}" << EOF
#!/bin/bash
# ==============================================================================
# ${cmd_name} - UVR Headless Runner CLI Wrapper
# ==============================================================================
# Auto-generated by install.sh
# Image: ${IMAGE_NAME}:${target}
# ==============================================================================

set -e

# Configuration
IMAGE="${IMAGE_NAME}:${target}"
MODELS_DIR="\${UVR_MODELS_DIR:-${MODELS_DIR}}"

# Ensure models directory exists
mkdir -p "\${MODELS_DIR}"

# Process arguments to handle file paths
DOCKER_ARGS=()
MOUNT_ARGS=()
PROCESSED_ARGS=()

# Track mounted directories to avoid duplicates
declare -A MOUNTED_DIRS

process_path() {
    local path="\$1"
    local mode="\$2"  # "ro" for input, "rw" for output
    
    # Skip if not a path
    if [[ ! "\$path" =~ ^[./~] ]] && [[ ! "\$path" =~ ^[a-zA-Z]: ]]; then
        echo "\$path"
        return
    fi
    
    # Expand path
    local abs_path
    if [[ "\$path" = /* ]]; then
        abs_path="\$path"
    elif [[ "\$path" = ~* ]]; then
        abs_path="\${path/#\~/$HOME}"
    else
        abs_path="\$(cd "\$(dirname "\$path")" 2>/dev/null && pwd)/\$(basename "\$path")"
    fi
    
    # Get directory
    local dir
    if [ -d "\$abs_path" ]; then
        dir="\$abs_path"
    else
        dir="\$(dirname "\$abs_path")"
    fi
    
    # Create directory if output
    if [ "\$mode" = "rw" ] && [ ! -d "\$dir" ]; then
        mkdir -p "\$dir"
    fi
    
    # Add mount if not already mounted
    if [ -z "\${MOUNTED_DIRS[\$dir]}" ] && [ -d "\$dir" ]; then
        MOUNTED_DIRS["\$dir"]=1
        MOUNT_ARGS+=("-v" "\${dir}:\${dir}:\${mode}")
    fi
    
    echo "\$abs_path"
}

# Parse arguments
while [[ \$# -gt 0 ]]; do
    case "\$1" in
        -i|--input)
            PROCESSED_ARGS+=("\$1")
            shift
            if [[ \$# -gt 0 ]]; then
                PROCESSED_ARGS+=("\$(process_path "\$1" "ro")")
                shift
            fi
            ;;
        -o|--output)
            PROCESSED_ARGS+=("\$1")
            shift
            if [[ \$# -gt 0 ]]; then
                PROCESSED_ARGS+=("\$(process_path "\$1" "rw")")
                shift
            fi
            ;;
        *)
            PROCESSED_ARGS+=("\$1")
            shift
            ;;
    esac
done

# Build docker run command
# Use -it only if running in a terminal
if [ -t 0 ] && [ -t 1 ]; then
    DOCKER_CMD=(docker run --rm -it)
else
    DOCKER_CMD=(docker run --rm)
fi
EOF

    # Add GPU flags conditionally
    if [ "${target}" = "gpu" ]; then
        cat >> "/tmp/${cmd_name}" << 'EOF'
DOCKER_CMD+=(--gpus all)
EOF
    fi

    cat >> "/tmp/${cmd_name}" << EOF
DOCKER_CMD+=(-v "\${MODELS_DIR}:/models")
DOCKER_CMD+=("\${MOUNT_ARGS[@]}")
DOCKER_CMD+=(-e "UVR_MODELS_DIR=/models")
DOCKER_CMD+=("\${IMAGE}")
DOCKER_CMD+=(${runner_script})
DOCKER_CMD+=("\${PROCESSED_ARGS[@]}")

# Run container
exec "\${DOCKER_CMD[@]}"
EOF

    # Install wrapper
    if [ -w "${INSTALL_DIR}" ]; then
        mv "/tmp/${cmd_name}" "${wrapper_path}"
        chmod +x "${wrapper_path}"
    else
        sudo mv "/tmp/${cmd_name}" "${wrapper_path}"
        sudo chmod +x "${wrapper_path}"
    fi
    
    log_success "Installed: ${wrapper_path}"
}

# ------------------------------------------------------------------------------
# Uninstall
# ------------------------------------------------------------------------------
uninstall() {
    log_info "Uninstalling UVR CLI wrappers..."
    
    local wrappers=("uvr" "uvr-mdx" "uvr-demucs" "uvr-vr")
    
    for wrapper in "${wrappers[@]}"; do
        local path="${INSTALL_DIR}/${wrapper}"
        if [ -f "${path}" ]; then
            if [ -w "${INSTALL_DIR}" ]; then
                rm -f "${path}"
            else
                sudo rm -f "${path}"
            fi
            log_success "Removed: ${path}"
        fi
    done
    
    log_info "Uninstallation complete."
    log_info "Note: Docker images and model cache were not removed."
    echo ""
    echo "To remove Docker images:"
    echo "  docker rmi ${IMAGE_NAME}:gpu ${IMAGE_NAME}:cpu"
    echo ""
    echo "To remove model cache:"
    echo "  rm -rf ${MODELS_DIR}"
}

# ------------------------------------------------------------------------------
# Main Installation
# ------------------------------------------------------------------------------
install() {
    local target="$1"
    
    print_banner
    
    # Check prerequisites
    check_docker
    
    # Auto-detect GPU if not specified
    if [ -z "${target}" ]; then
        log_info "Auto-detecting GPU support..."
        target=$(detect_gpu)
        log_info "Detected: ${target}"
    fi
    
    # Create models directory
    log_info "Creating models directory: ${MODELS_DIR}"
    mkdir -p "${MODELS_DIR}"
    mkdir -p "${MODELS_DIR}/VR_Models"
    mkdir -p "${MODELS_DIR}/MDX_Net_Models"
    mkdir -p "${MODELS_DIR}/Demucs_Models"
    
    # Build Docker image
    build_image "${target}"
    
    # Create wrapper scripts
    log_info "Installing CLI wrappers to ${INSTALL_DIR}..."
    
    create_wrapper "uvr-mdx" "uvr-mdx" "${target}"
    create_wrapper "uvr-demucs" "uvr-demucs" "${target}"
    create_wrapper "uvr-vr" "uvr-vr" "${target}"
    create_wrapper "uvr" "uvr" "${target}"
    
    # Print success message
    echo ""
    log_success "Installation complete!"
    echo ""
    echo -e "${GREEN}You can now use these commands:${NC}"
    echo ""
    echo "  uvr-mdx -m \"Kim Vocal 2\" -i song.wav -o output/"
    echo "  uvr-demucs -m htdemucs -i song.wav -o output/"
    echo "  uvr-vr -m \"UVR-De-Echo-Normal\" -i song.wav -o output/"
    echo ""
    echo "  uvr mdx --list          # List MDX models"
    echo "  uvr demucs --list       # List Demucs models"
    echo "  uvr vr --list           # List VR models"
    echo "  uvr info                # Show system info"
    echo ""
    echo -e "${CYAN}Models will be cached in: ${MODELS_DIR}${NC}"
    echo ""
    
    if [ "${target}" = "gpu" ]; then
        echo -e "${GREEN}GPU acceleration is enabled!${NC}"
    else
        echo -e "${YELLOW}Running in CPU mode.${NC}"
        echo "For GPU support, ensure NVIDIA drivers and nvidia-container-toolkit are installed."
    fi
}

# ------------------------------------------------------------------------------
# Parse Arguments
# ------------------------------------------------------------------------------
TARGET=""
ACTION="install"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cpu)
            TARGET="cpu"
            shift
            ;;
        --gpu)
            TARGET="gpu"
            shift
            ;;
        --uninstall|uninstall)
            ACTION="uninstall"
            shift
            ;;
        --help|-h)
            print_banner
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --cpu        Force CPU-only installation"
            echo "  --gpu        Force GPU installation"
            echo "  --uninstall  Remove installed CLI wrappers"
            echo "  --help       Show this help message"
            echo ""
            echo "Environment Variables:"
            echo "  UVR_INSTALL_DIR   Installation directory (default: /usr/local/bin)"
            echo "  UVR_MODELS_DIR    Model cache directory (default: ~/.uvr_models)"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Execute
case "${ACTION}" in
    install)
        install "${TARGET}"
        ;;
    uninstall)
        uninstall
        ;;
esac
